#!/bin/bash
version: "3.3"
services:
  openaibot:
    container_name: openaibot
    image: node:latest
    restart: always
    environment:
      - BOT_TOKEN=0000
      - OPEN_AI_TOKEN=0000

      - API_ID=000
      - API_HASH=000
      - PHONE=000
    command: sh /var/www/app/init.sh
    volumes:
      - "./:/var/www/app"
