#!/bin/bash
version: "3.3"
services:
  openaibot:
    container_name: openaibot
    image: node:18
    restart: always
    environment:
      - APP_LOCALE=ru
      - TIMEOUT_MSG_EDIT=10000
      - OPEN_AI_TOKEN=
      # for bot
      - BOT_TOKEN=
      # for user
      - API_ID=
      - API_HASH=
      - PHONE=
    command: sh /var/www/app/init.sh
    volumes:
      - "./:/var/www/app"
