#!/bin/bash
version: "3.3"
services:
  openaibot:
    container_name: openaibot
    image: node:18
    restart: always
    environment:
      - OPEN_AI_TOKEN=000
      # for bot
      - BOT_TOKEN=000
      # for user
      - API_ID=000
      - API_HASH=000
      - PHONE=000
    command: sh /var/www/app/init_bot.sh
#    command: sh /var/www/app/init_user.sh
    volumes:
      - "./:/var/www/app"
