name: Docker Image
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run:  docker build . --file Dockerfile --tag upachko/chat-gpt-tg-bot:${{ github.sha }} --tag upachko/chat-gpt-tg-bot:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DHCL }}
          password: ${{ secrets.DCHP }}
      - name: Push To Docker Hub
        run: docker push -a upachko/chat-gpt-tg-bot
