name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.4
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_REMOTE_URL: ${{ github.server_url }}/${{ github.repository }}
          QODANA_BRANCH: ${GITHUB_REF##*/}
          QODANA_REVISION: ${{ github.sha }}
          QODANA_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          args: --pr-mode,false
      - name: "GitHub code scanning"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
